config/routes.rb
Rails.application.routes.draw do
  
  resources :categories do
    resources :posts
  end
  
  resources :posts do
  	 resources :comments
  end
  
  resources :posts

 	resources :comments



 root 'static_pages#home'
 get '/home', to: 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
 
 has_many :posts

 validates :name, :length => {
    :minimum   => 2,
    :maximum   => 300,
    :tokenizer => lambda { |str| str.split.capitalize! },
    :too_short => "must have at least 2 words"
    }, format: { with: /[a-zA-Z_\-.]/,
    message: "only allows letters and ." }

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

     validates :author, presence: true, :length => {
    :minimum   => 2,
    :maximum   => 300,
    :tokenizer => lambda { |str| str.split.map(&:capitalize) },
    :too_short => "must have at least 2 words"
    }, format: { with: /[a-zA-Z_\-.]/,
    message: "only allows letters and ." }

    validates :content, presence: true
end

app/models/post.rb
require 'file_size_validator' 

class Post < ApplicationRecord

  belongs_to :category
  has_many :comments 
  mount_uploader :file, FileUploader

   validates :name, presence: true, :length => {
    :minimum   => 2,
    :maximum   => 300,
    :tokenizer => lambda { |str| str.split.map(&:capitalize) },
    :too_short => "must have at least 2 words"
    }, format: { with: /[a-zA-Z_\-.]/,
    message: "only allows letters and ." }

   validates :file, :file_size => { maximum: 2.megabytes.to_i  }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @posts = Post.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 skip_before_action :verify_authenticity_token

	 def create
	@post = Post.find(params[:post_id])
 @comment = @post.comments.create(comment_params)
  respond_to do |format|
   format.js { @comment }
   format.html { redirect_to @post }
   format.json { render :comment, status: :created, location: @comment }
  end
end

def comment_params
 params.require(:comment).permit(:author, :content)
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_category

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comment.post_id = @post.id
  end


  def new
    @post = Post.new
  end

  def edit
   @post = @category.posts.find(params[:id])
  end

  def create
    @post = @category.posts.build(post_params)
     @post.file = params[:file]
      if @post.save
       redirect_to category_url(@category)
      else
       render 'new'
      end
    
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to category_post_url(@category, @post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to category_path(@category), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
    def set_post
      @post = Post.find(params[:id])
    end
    
    def set_category
      @category = Category.find(params[:category_id])
    end
   
    def post_params
      params.require(:post).permit(:name, :content, :file, :category_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
		@categories = Category.all
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

 <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <thead style= "background-color: #bdacac; font-family: 'Mark-Pro';font-size: 12.7px">
    <tr class="text-gray">
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/_posts.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

 <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <thead style= "background-color: #bdacac; font-family: 'Mark-Pro';font-size: 12.7px">
    <tr class="text-gray">
      <th>Name</th>
      <th>Content</th>
      <th>File</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @category.posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= truncate(strip_tags(post.content), length:80) %></td>
        <td><%= post.file %></td>
        <td><%= post.category.name %></td>
        <td><%= link_to 'Show', category_post_path(@category, post) %></td>
        <td><%= link_to 'Edit', edit_post_path(@category, post) %></td>
        <td><%= link_to 'Destroy', category_post_path(@category, post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

 <table data-toggle="table" width="100%" border="0" cellspacing="0" cellpadding="0">
  <thead style= "background-color: #bdacac; font-family: 'Liberation Sans';font-size: 12.7px">
    <tr class="text-gray">
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %> |
<%= link_to 'New Post', new_category_post_path(@category, @post) %>

<%= render partial: 'posts' %>

app/views/comments/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author %></h4>
  <p class="text-gray"><%= comment.content %></p>
</div>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_with(model: @comment, url: [ @post, @comment ], remote: true) do |f| %>
 <p>
  <%= f.label :author, "Your Name" %><br/>
  <%= f.text_field :author %>
 </p>
 <p>
  <%= f.label :content %><br/>
  <%= f.text_area :content %>
 </p>
 <p>
  <%= f.submit 'Submit' :save %>
 </p>
<% end %>

app/views/comments/comment.js.erb
$("#comment").on("ajax:beforeSend", function(){
   window.location.reload();
}).on("ajax:complete", function(){
  //preloader hide
});

app/views/comments/create.js.erb
$('#comment').html("<%=j render(@comment) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogpost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag('jquery.js') %>
    <%= javascript_include_tag('bootstrap.js') %>
    <%= javascript_include_tag('jquery_ujs.js') %>
  <meta name="author" content="rghost">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800,400italic">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>

  <body>
    <div class="allcontain">
     <div class="header">
      <ul class="logreg">
        <li><a href="#""><i class="fas fa-atlas"></i></a></li>
        <li><a href="#"><i class="fas fa-arrow-alt-circle-down"></i></a></li>
        <li><a href="#"><i class="fas fa-alicorn"></i></a></li>
        <li><a href="#"><i class="fas fa-archive"></i></a></li>
      </ul>
      <ul class="callme">
        <li>BLOG</li>
      </ul>
      <ul class="logreg">
        <% if current_page? categories_path %>
        <li><a href="<%= home_path %>">Home </a> </li>
        <% else %>
        <!--<li><a href="#">Posts </a> </li> -->
        <% end %>
      </ul>
  </div>
    <%= yield %>
  </body>
</html>

app/views/posts/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author %></h4>
  <p class="text-gray"><%= comment.content %></p>
</div>

app/views/posts/_comment_form.html.erb
<h3>Post a Comment</h3>

<%= form_with(model: @comment, url: [ @post, @comment ], remote: true) do |f| %>
 <p>
  <%= f.label :author, "Your Name" %><br/>
  <%= f.text_field :author %>
 </p>
 <p>
  <%= f.label :content %><br/>
  <%= f.text_area :content %>
 </p>
 <p>
  <%= f.submit 'Submit' %>
 </p>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: @post, url: [ @category, @post ], local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/comment.js.erb
$("#comment").on("ajax:beforeSend", function(){
   window.location.reload();
}).on("ajax:complete", function(){
  //preloader hide
});

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', category_post_path(@category, @post) %> |
<%= link_to 'Back', category_posts_path(@category, @post) %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

 <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <thead style= "background-color: #bdacac; font-family: 'Mark-Pro';font-size: 12.7px">
    <tr class="text-gray">
      <th>Name</th>
      <th>Content</th>
      <th>File</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @category.posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= truncate(strip_tags(post.content), length:80) %></td>
        <td><%= post.file %></td>
        <td><%= post.category.name %></td>
        <td><%= link_to 'Show', category_post_path(@category, post) %></td>
        <td><%= link_to 'Edit', edit_post_path(@category, post) %></td>
        <td><%= link_to 'Destroy', category_post_path(@category, post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post, category: @category %>

<%= link_to 'Back', @category %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>File:</strong>
  <%= file_field_tag(@post.file.url) if @post.file? %>
</p>

<p>
  <strong>Category:</strong>
  <%= @post.category.name %>
</p>

<%= link_to 'Edit', edit_category_post_path(@category, @post) %> |
<%= link_to 'Back', @category %>

<h3>Comments</h3>
<%= render partial: 'posts/comment', collection: @post.comments, remote: true %>
<%= render 'comment_form', comment: Comment.new, post_id: @post.id %>

app/views/static_pages/home.html.erb
<h2 class="text gray">Blog </h2>
<%= render partial: 'categories/index' %> 